# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bae1d2b3e14b9e848a85fa6a80421d740f232b50d828324bb6c75ee1f4a238fed89dc5335b62809ad3811f0d270e235f68f4a9ba410cb9ffb797de3870b99efa

test:
  secret_key_base: f6c90fccfebc28fe3cb9ea68aee929ab0943e1579f228980a5aa175974e2602967e36522ccd3fd08295c71c7d218a11b21257e6bfb07c2ecd1e9009167642a97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
